parameters:
    database_driver:   pdo_sqlsrv
    database_host:     'tcp:hostname.database.windows.net'
    database_port:     ~
    database_name:     taskapp
    database_user:     user@hostname
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    windows_azure_blob: UseDevelopmentStorage=true
    windows_azure_table: UseDevelopmentStorage=true

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

